### ISSUE TITLE
[마이페이지] 최근 본 작품 글자 넘침

### ISSUE THREAD

**Issue by selinakk** [selinakk/PageOn#23]
<img width="423" alt="image" src="https://github.com/user-attachments/assets/7fe50f23-ae26-4cec-9425-275e1e9f171b">

제목이 좀만 길어도 본문 내용이 넘쳐서 일단 desc는 주석했습니다
주석했는데도 제목이 긴 경우에는 본문이 넘칩니다

수정이 필요하진 않고 추후 개선사항으로 남겨둡니다

**Comment by selinakk** [comment]
@KyunyeonKim 님

**Comment by KyunyeonKim** [comment]
제가 수정하겠습니다 감사합니다.
